name: inital_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cloud_firestore: ^4.4.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/refactor/RefactorLogo.png